name: Publish Python distribution to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install uv
        run: pip install uv
      - name: Build package
        run: uv build
      - name: Install test dependencies
        run: uvx install -r requirements-dev.txt
      - name: Lint with ruff
        run: ruff .
      - name: Run tests
        run: pytest
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload dist/* 